### ISSUE TITLE
Opening and reading the file

### ISSUE THREAD

**Issue by 5skr0ll3r** [5skr0ll3r/Cthulhu#3]
`Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/htb-5skr0ll3r/Desktop/webserver.py", line 46, in handler
    if stat(folder, file) != "False":
  File "/home/htb-5skr0ll3r/Desktop/webserver.py", line 21, in stat
    with open(text, "r") as ftext:
IsADirectoryError: [Errno 21] Is a directory: 'ww1/'
`

**Comment by 5skr0ll3r** [comment]
is fixed (for now)
