### ISSUE TITLE
OSError 

### ISSUE THREAD

**Issue by 5skr0ll3r** [5skr0ll3r/Cthulhu#7]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sskroller/My-Tools/Pyscripts/Cthulhu/cthulhu.py", line 52, in connections_handler
    packet = connection.recv(3000)
OSError: [Errno 9] Bad file descriptor

**Comment by 5skr0ll3r** [comment]
fixed
