### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by 5skr0ll3r** [5skr0ll3r/Cthulhu#9]
Image wont be uploaded (have to debug this)

**Comment by 5skr0ll3r** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sskroller/Desktop/Cthulhu/cthulhu.py", line 80, in connections_handler
    code = read_file(Project_Path,req_file_path,file_ext,imag_ext)
  File "/home/sskroller/Desktop/Cthulhu/cthulhu.py", line 49, in read_file
    code = op_file.read()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by 5skr0ll3r** [comment]
also propably have to send image as chunks

**Comment by 5skr0ll3r** [comment]
How much data can HTTP send?
4 Answers. The HTTP specification doesn't impose a specific size limit for posts. They will usually be limited by either the web server or the programming technology used to process the form submission. No limit by specification.


so no i dont lel

**Comment by 5skr0ll3r** [comment]
<img width="1278" alt="Screenshot 2021-10-23 at 11 24 17 PM" src="https://user-images.githubusercontent.com/47701859/138570485-16c088f9-c400-4ef1-b9de-cc3206b47085.png">
